### ISSUE TITLE
If the object is locked, when the user selects a source datastream, the "object locked" message shows up twice. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_xslt#2]
## Expected Behaviour

1. user should only see the dropdown of available XSLTs and no drupal message between the source dropdown and the xslt dropdown. 

## Current Behaviour

![image](https://user-images.githubusercontent.com/6600070/54463355-67662980-4738-11e9-8c5f-9031e082ec74.png)

## Steps to Reproduce (for bugs)

1. Go to specified URL
2. Lock object
3. Go to Manage>Add/change a datastream with XSLKT
4. Select CWRC datastream

## Your Environment

* URL: https://dev-01.cwrc.ca/islandora/object/islandora%3A0b511ede-b6b1-4f9e-b7c7-42af03c741a0
* Browser Name: Chrome 72.0.3626.119 (Incognito Window)
* Operating System: MacOS Mojave (10.14.3)

**Comment by nikathone** [comment]
https://github.com/cwrc/cwrc_xslt/commit/ee5af20effe78e1e4a782a495b8b261afee6323d should fix this.

**Comment by ilovan** [comment]
yup, this one seems to be fixed, thanks, @nikathone
